#!/usr/bin/env bash

source docker/docker-functions
source docker-functions 2>/dev/null # Kun for at IntelliJ skal kunne linke funksjoner (hack!)

verify() {
    buildImage docker.io/difi jenkins-agent DEV-SNAPSHOT
}

deliver() {
    [[ $# -eq 3 ]] || { >&2 echo "Usage: $0 $FUNCNAME VERSION USERNAME PASSWORD"; return 1; }
    local version=$1
    local username=$2
    local password=$3
    buildImage docker.io/difi jenkins-agent ${version} || return 1
    pushImage docker.io/difi jenkins-agent ${version} "${username}" "${password}" || return 1
}

case $1 in
    verify)
        shift
        verify || exit 1
        ;;
    deliver)
        shift
        deliver ${@} || exit 1
        ;;
    *)
        >&2 echo "Usage $0 deliver|verify ..."
        exit 1
        ;;
esac
